import './globals.css'
import styles from './page.module.css'
import { Poppins } from 'next/font/google'
// import Head from "next/head";
import Header from './components/Header'

const poppins = Poppins({
    weight: ['400', '700'],
    subsets: ['latin'],
});

export const metadata = {
  title: 'Responsive Navbar',
  description: 'Generated by create next app',
}

export default function RootLayout({children}){
  return (
      <html lang="en">
      <body className={poppins.className}>
      <Header/>
      <main className='container'>{children}</main>
      </body>
      </html>
  )
}
